name: Test All Events

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  issues:
    types: [opened, closed, reopened, labeled]
  release:
    types: [published]
  schedule:
    - cron: "0 0 * * *"
  workflow_dispatch:

jobs:
  test-all-events:
    runs-on: ubuntu-latest
    
    steps:
      # Step 1: Checkout the code
      - name: Checkout the code
        uses: actions/checkout@v3

      # Step 2: Display GitHub Event Information
      - name: Display GitHub Event Information
        run: |
          echo "Event Name: ${{ github.event_name }}"
          echo "Repository: ${{ github.repository }}"
          echo "Branch: ${{ github.ref }}"
          echo "Actor: ${{ github.actor }}"
          echo "Event Path: ${{ github.event_path }}"

      # Step 3: Check if it's a push or pull request
      - name: Check if it's a push or pull request
        run: |
          if [ "${{ github.event_name }}" == "push" ]; then
            echo "Triggered by a push event"
          elif [ "${{ github.event_name }}" == "pull_request" ]; then
            echo "Triggered by a pull request"
          else
            echo "Triggered by another event"
          fi

      # Step 4: Handle scheduled or manual triggers
      - name: Schedule or Manual Trigger
        run: |
          if [ "${{ github.event_name }}" == "schedule" ]; then
            echo "This is a scheduled event"
          elif [ "${{ github.event_name }}" == "workflow_dispatch" ]; then
            echo "This workflow was manually triggered"
          fi

      # Step 5: Show event details for issues or releases
      - name: Show event details for issues or releases
        run: |
          if [ "${{ github.event_name }}" == "issues" ]; then
            echo "Issue event detected!"
            echo "Action: ${{ github.event.action }}"
            echo "Issue Title: ${{ github.event.issue.title }}"
          elif [ "${{ github.event_name }}" == "release" ]; then
            echo "Release event detected!"
            echo "Release Tag: ${{ github.event.release.tag_name }}"
          fi

      # Step 6: Check if the file test.txt exists
      - name: Check if test.txt exists
        run: |
          if [ ! -f "test.txt" ]; then
            echo "File test.txt not found!"
            exit 1
          else
            echo "test.txt found!"
          fi

      # Step 7: Send email on success with test.txt attached
      - name: Send Email on Success
        if: success()
        uses: dawidd6/action-send-mail@v3
        with:
          server_address: smtp.gmail.com
          server_port: 465
          username: ${{ secrets.EMAIL_USERNAME }}
          password: ${{ secrets.EMAIL_PASSWORD }}
          subject: "GitHub Actions Job Success"
          body: "The job has completed successfully."
          to: hari.narayan.k158@gmail.com
          from: ${{ secrets.EMAIL_USERNAME }}
          attachments: test.txt
