name: CI Pipeline 

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  repository_dispatch:
    types: [trigger-build]
  workflow_dispatch:  # Allows manual triggering of the workflow
  schedule:
    - cron: '0 0 * * *'  # Runs the workflow daily at midnight

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: pip install smtplib email

    - name: Run echo command
      run: echo "Hello, this is a test run!"

    - name: Send email notification
      run: python send_email.py
      env:
        SMTP_USERNAME: ${{ secrets.MKEMAIL_USERNAME }}
        SMTP_PASSWORD: ${{ secrets.MKEMAIL_PASSWORD }}
