name: Check Run Test

on:
  check_run:
    types: [created, completed]

jobs:
  test-check-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Print Check Run Info
      run: |
        echo "Check Run Event Triggered"
        echo "Check Run ID: ${{ github.event.check_run.id }}"
        echo "Check Run Name: ${{ github.event.check_run.name }}"
        echo "Check Run Status: ${{ github.event.check_run.status }}"
        echo "Check Run Conclusion: ${{ github.event.check_run.conclusion }}"
